### ISSUE TITLE
NameError: name 'driver' is not defined

### ISSUE THREAD

**Issue by stickerx** [heysh/alienwareArena#1]
get this error 

> Traceback (most recent call last):
  File "C:\Users\stickerx\Desktop\alienwareArena-master\upvote.py", line 58, in <module>
    main()
  File "C:\Users\stickerx\Desktop\alienwareArena-master\upvote.py", line 55, in main
    upvote(driver, upvLinks)
NameError: name 'driver' is not defined

Press Enter or Esc to close console...

**Comment by heysh** [comment]
Hey, I'm unsure why the main function in the upvote.py file is being called. From what I remember, the main function should only be called in the file called main.py.

**Comment by stickerx** [comment]
can you fix this error

**Comment by heysh** [comment]
Can you tell me what you did to get this error (e.g. executing the upvote.py file)?

**Comment by stickerx** [comment]
get this error

NameError: name 'driver' is not defined

**Comment by heysh** [comment]
Can you tell me which file you are executing?

**Comment by stickerx** [comment]
executing upvote.py

**Comment by stickerx** [comment]
line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by heysh** [comment]
You should be trying to execute main.py

**Comment by stickerx** [comment]
Now i get this error

 line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by heysh** [comment]
Hmm... I'm not sure about this one. Can you send me the complete error message in case you have only sent the final part?

**Comment by stickerx** [comment]
![2018-12-07_164401](https://user-images.githubusercontent.com/41187653/49660968-cf251e00-fa3f-11e8-9c6b-9f1b9714d21d.png)

**Comment by stickerx** [comment]
![2018-12-07_164401](https://user-images.githubusercontent.com/41187653/49661046-fda2f900-fa3f-11e8-8d98-a6367f53ec8a.png)

**Comment by heysh** [comment]
Thanks for the screenshot, I can see the problem now. I will update my program soon.

**Comment by stickerx** [comment]
Good luck dude

when updated i will test him

**Comment by heysh** [comment]
I've updated the program now.

**Comment by stickerx** [comment]
Now i get this error

![2018-12-07_185821](https://user-images.githubusercontent.com/41187653/49667248-73b05b80-fa52-11e8-8bd2-05b0a226e9cc.png)

**Comment by heysh** [comment]
Looks like some of the other errors are gone, but the last one is still there. Can you tell me which version of Firefox you have installed?

**Comment by stickerx** [comment]
i dont have Firefox i use chrome

**Comment by heysh** [comment]
That might be the problem. Try installing the latest version of Firefox.
